set hive.cli.print.header  = TRUE;

SELECT a.zip_code , COUNT(DISTINCT(a.incident_number_wo_year)) 
FROM (SELECT pincidents.*, add.average_income , add.education, add.population  FROM project.pincidents INNER JOIN project.add ON pincidents.zip_code = add.zipcode) AS a
WHERE a.average_income > '55,653' GROUP BY a.zip_code;

SELECT b.zip_code, COUNT(DISTINCT(b.incident_number_wo_year))
FROM (SELECT pincidents.* , add.average_income, add.education, add.population FROM project.pincidents INNER JOIN project.add ON pincidents.zip_code = add.zipcode) AS b
WHERE b.average_income < '55,653' GROUP BY b.zip_code;
