set hive.cli.print.header= TRUE;

SELECT a.gang_related_offense , COUNT(DISTINCT(a.incident_number_wo_year)) FROM
(SELECT pincidents.* , add.average_income FROM project.pincidents INNER JOIN project.add
ON pincidents.zip_code = add.zipcode) AS a
WHERE a.average_income > '55,653'
GROUP BY a.gang_related_offense;


SELECT a.gang_related_offense , COUNT(DISTINCT(a.incident_number_wo_year)) FROM
(SELECT pincidents.* , add.average_income FROM project.pincidents INNER JOIN project.add
ON pincidents.zip_code = add.zipcode) AS a
WHERE a.average_income < '55,653'
GROUP BY a.gang_related_offense;

SELECT a.drug_related_incident , COUNT(DISTINCT(a.incident_number_wo_year)) FROM
(SELECT pincidents.* , add.average_income FROM project.pincidents INNER JOIN project.add
ON pincidents.zip_code = add.zipcode) AS a
WHERE a.average_income > '55,653'
GROUP BY a.drug_related_incident;


SELECT a.drug_related_incident , COUNT(DISTINCT(a.incident_number_wo_year)) FROM
(SELECT pincidents.* , add.average_income FROM project.pincidents INNER JOIN project.add
ON pincidents.zip_code = add.zipcode) AS a
WHERE a.average_income < '55,653'
GROUP BY a.drug_related_incident;

