set hive.cli.print.header = TRUE;

SELECT a.UCR_offense_description, a.month1_of_occurence, a.year1_of_occurrence, a.complainant_gender, COUNT(DISTINCT(incident_number_wo_year)) FROM
(SELECT pincidents.*, add.average_income, add.education FROM project.pincidents INNER JOIN project.add 
ON pincidents.zip_code = add.zipcode) AS a
WHERE a.average_income < '55,653' AND a.education < 85
GROUP BY a.UCR_offense_description, a.month1_of_occurence, a.year1_of_occurrence, a.complainant_gender;
